### ISSUE TITLE
Deploying tutorial application error - cannot find the current segment/subsegment, please make sure you have a segment open

### ISSUE THREAD

**Issue by dflorian** [gdoumenc/coworks#9]
When running the initial TechMS quickstart - https://coworks.readthedocs.io/en/latest/tech_quickstart.html - calling the locally served apps render error.

**To Reproduce**
follow [documentation](https://coworks.readthedocs.io/en/latest/tech_quickstart.html) until testing the microservice:
Test this microservice locally:
`(project)` $ cws -m first -s app run
Serving on http://127.0.0.1:8000

On another terminal enter:
`(project)` $ curl http://127.0.0.1:8000
{"Code":"InternalServerError","Message":"An internal server error occurred."}floriand-macbookpro:~ floriand$

on first terminal:
cannot find the current segment/subsegment, please make sure you have a segment open
simplemicroservice - ERROR - Caught exception for path /

**Comment by gdoumenc** [comment]
Right, segment/subsegment are aws xray concepts, so should not be defined for local run... Will fix quickly.

Which branch?

**Comment by dflorian** [comment]
using cws from pipenv, so I'm guessing master.
I'm also guessing it's relevant across branches ;)

**Comment by gdoumenc** [comment]
Issue fixed with version 0.3.5
